from fpdf import FPDF
import os

class PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'Internship Certificate', 0, 1, 'C')

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 10)
        self.cell(0, 10, 'Generated by Admin Panel', 0, 0, 'C')

def generate_attestation(name, subject, supervisor, output_path):
    pdf = PDF()
    pdf.add_page()
    pdf.set_font('Arial', '', 12)
    pdf.ln(10)
    pdf.multi_cell(0, 10, f"This is to certify that {name} successfully completed an internship on the subject:\n\n"
                          f"\"{subject}\"\n\n"
                          f"under the supervision of {supervisor}.\n\n"
                          f"We acknowledge their dedication and contribution during this period.\n\n"
                          f"Date: ________________\n\nSignature: ________________")
    pdf.output(output_path)
