"""Ajout colonnes dans Offer

Revision ID: f34b996db690
Revises: 
Create Date: 2025-07-13 10:48:24.754235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34b996db690'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('university', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('education', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('motivation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cv_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('motivation_filename', sa.String(length=255), nullable=True))

    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nb_souhaitee', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('competences', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('duree', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('date_debut', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('date_fin', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.drop_column('date_fin')
        batch_op.drop_column('date_debut')
        batch_op.drop_column('duree')
        batch_op.drop_column('competences')
        batch_op.drop_column('nb_souhaitee')

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('motivation_filename')
        batch_op.drop_column('cv_filename')
        batch_op.drop_column('motivation')
        batch_op.drop_column('duration')
        batch_op.drop_column('education')
        batch_op.drop_column('university')
        batch_op.drop_column('email')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
